name: release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: build-${{ github.sha }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download previous build artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          commit: ${{ github.sha }}
          event: push
          name: VanillaTweaks

      - name: Parse tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Create release and changelog
        uses: MC-Machinations/auto-release-changelog@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Vanilla Tweaks ${{ steps.vars.outputs.tag }}
          pre-release: ${{ endsWith(steps.vars.outputs.tag, '-dev') }}
          skip-prereleases: true
          files: |
            VanillaTweaks-Bukkit.jar
            VanillaTweaks-Paper.jar
            LICENSE
